### ISSUE TITLE
Extract **Static fonts** from the **variable font SITKA**  in **Windows** 10 & 11 (Sorry if off-topic)

### ISSUE THREAD

**Issue by JimEBlevins** [TiroTypeworks/TiroTools#11]
Hi Tiro Typeworks team!

This seemed like a reasonable place to raise this issue, rather than in an email to your firm (which I would be happy to do so, if more appropriate). Please erase if inappropriate. 

With permission, I quote from my discussion with **customer service** at Microsoft **Windows**

> January 23, 2023, 12:21 
> I wish to extract **static** TrueType files (*.ttf or *.otf) from the **Sitka variable-fonts** (`SitkaVF.ttf `and SitkaVF-Italic.ttf). 
> This is to have access to the **SMALLCAPS** for Bold (and Bold Italics) in LaTeX via the **LaTeX** package **fontspec** (CTAN).
> 
> January 23, 2023, 12:27
> Every Windows distribution has a font library. Windows 10 and 11 have the font SITKA, which is a **variable font.** This means that the conventional styles (regular, bold, italic, and bold-italic ... and many more) are located in one variable-font file, rather than in 4+ files. For my application (the mathematical typesetting program LaTeX and its package FONTSPEC), I want to have 4 or more STATIC font files, with the traditional styles (regular, bold, italic, and bold italic). 
> This is a common problem. On **GitHub**, many OpenType free and open-source software (FOOS) font distributions have **one variable-font file**  complemented with a folder containing 4+ **static** font files. It would be useful for Microsoft to generate such files for Windows users, which could be distributed securely on the Microsoft Store.  It would take one day for professional typographers to generate such files, I would like to believe. 

> January 23, 2023, 12:32 
> It seems you are **suggesting some features for windows** which is not yet available within windows, am I right?
> January 23, 2023, 12:33

> It does seem available, if one wishes to use **Visual Studio** and the [IDWriteGdilnterop](https://learn.microsoft.com/en-us/windows/win32/api/dwrite/nf-dwrite-idwritegdiinterop-createfontfromlogfont) ... function. 
> Learning about the font database and the internal workings of Windows is too much for me and for most users. 

> In some sense, yes, I am suggesting the distribution of static fonts, on demand, likely through the Windows store, the way that Windows users can easily download Georgia Pro, Arial Nova, Verdana Pro, etc. (Georgia and Verdana, like Sitka, were developed by Matthew Carter.) 
> January 23, 2023, 12:38 pmJim

ADDED: I am suggesting something like a "SITKA STATIC" package, which would contain all the font-files that appear in my Windows font directory as separate files), which I could download like Georgia Pro freely from the Microsoft Store.

> For **application** such as **Visual studio**, we have a dedicated team to assist you. We are only trained on **windows** and can help you with Windows related issues. We can not add any new feature or work on any new feature. 
> January 23, 2023, 12:39
> If you are suggesting some features that can be integrated with windows in future, you will have to go with **Feedback hub application**. Once you provide your feedback using the feedback hub app, it will reach the Research and development team, so that it can be implemented in the future. 
> January 23, 2023, 12:41

> May I **copy and post this** (leaving out your name, [...]) on Github? Matthew Carter developed Sitka with the help of the **Tiro Typeworks** type-foundry, which is active on Github.  They likely _could_ contact their colleagues at Microsoft Windows design and get such a project rolling, if appropriate. 
> January 23, 2023, 12:40 pmJim
> Or do your Terms of Service prohibit such copy and pasting (even with anonymization)? 
> January 23, 2023, 12:42 pmJim

**> Sure you  can.**
> January 23, 2023, 12:42 [Nice person]

**Comment by tiroj** [comment]
I’ll bring this to the attention of the project manager for Sitka at Microsoft. Note, however, that we have gone to a lot of work to move Sitka to a variable font build and deliverable precisely because that is how Microsoft wish to make the font available to Windows users, and maintaining a synchronised build and delivery stream for static fonts is unlikely to appeal, especially if you wanted separate smallcap fonts as you seem to suggest. That would be a couple of steps backwards technologically, not only from variable fonts but from OpenType Layout for glyph variants.

**Comment by tiroj** [comment]
PS. This is not really an appropriate location for this issue, since it does not relate to the contents or purpose of Tiro’s tool repo, but I will leave the issue open for a bit so the PM has a chance to review and comment if he wishes.

**Comment by khaledhosny** [comment]
FWIW, you can use variable fonts with LaTeX and fontspec if you use LuaTeX as engine. Also a separate small caps file is not needed.

**Comment by JimEBlevins** [comment]
> FWIW, you can use variable fonts with LaTeX and fontspec if you use LuaTeX as engine. Also a separate small caps file is not needed.

As always, Khaled / Dr. Hosny, I am grateful for your work. 

Here, I should specify that the [regular] and italics fonts work fine, but LaTex/LuaTeX/TexStudio cannot find the bold files. Perhaps I should give an explicit directory address?

I have been using **LuaTeX** with LaTeX and **fontspec**.

The [15 January 2022 manual for fontspec ](https://texdoc.org/serve/fontspec/0) does not discuss variable fonts. It contains 6 instances of the word "variable", none of which are connected to variable fonts. 

A 2021 discussion of "recent" or "new" variable-font capabilities of fontspec did not work for me: 
- [How to use Sitka (from tex.stackexchange)](https://tex.stackexchange.com/questions/615562/how-to-use-sitka-or-what-is-the-closest-similar-font)

**Comment by JimEBlevins** [comment]
> I’ll bring this to the attention of the project manager for Sitka at Microsoft. Note, however, that we have gone to a lot of work to move Sitka to a variable font build and deliverable precisely because that is how Microsoft wish to make the font available to Windows users, and maintaining a synchronised build and delivery stream for static fonts is unlikely to appeal, especially if you wanted separate smallcap fonts as you seem to suggest. That would be a couple of steps backwards technologically, not only from variable fonts but from OpenType Layout for glyph variants.

Thanks for your answer. 

Sitka works wonderfully for Microsoft Word and Libre Office Writer, and so the issue lies between fontspec and its documentation.

**Comment by khaledhosny** [comment]
> > FWIW, you can use variable fonts with LaTeX and fontspec if you use LuaTeX as engine. Also a separate small caps file is not needed.
> 
> As always, Khaled / Dr. Hosny, I am grateful for your work.
> 
> Here, I should specify that the [regular] and italics fonts work fine, but LaTex/LuaTeX/TexStudio cannot find the bold files. Perhaps I should give an explicit directory address?
> 
> I have been using **LuaTeX** with LaTeX and **fontspec**.

That is probably a [luaotfload](https://github.com/latex3/luaotfload) bug/limitation, better to ask on its bug tracker.

> The [15 January 2022 manual for fontspec ](https://texdoc.org/serve/fontspec/0) does not discuss variable fonts. It contains 6 instances of the word "variable", none of which are connected to variable fonts.

Indeed, it looks like fontspec lacks high level support for controlling variable font axes.

> A 2021 discussion of "recent" or "new" variable-font capabilities of fontspec did not work for me:
> 
>   * [How to use Sitka (from tex.stackexchange)](https://tex.stackexchange.com/questions/615562/how-to-use-sitka-or-what-is-the-closest-similar-font)

I don’t have variable Sitka to test, but I tested with EB Garamond variable version, and got it to work with the following:
```tex
\documentclass{article}
\usepackage{fontspec}
\setmainfont{EB Garamond}
[
  BoldFont           = {EB Garamond}, % suppress font shape undefined warning
  BoldItalicFont     = {EB Garamond/I}, % suppress font shape undefined warning
  BoldFeatures       = {RawFeature={axis={wght=Bold}}},
  BoldItalicFeatures = {RawFeature={axis={wght=Bold}}},
]
\begin{document}
Hello \textbf{World}

\textit{Hello \textbf{World}}
\end{document}
```

**Comment by tiroj** [comment]
Closing, as we don’t own the Sitka fonts are not able to either directly provide a solution to this issue or to recommend one.
