### ISSUE TITLE
CFF2 table in static OTFs

### ISSUE THREAD

**Issue by tiroj** [TiroTypeworks/TiroTools#22]
Using the build options that instantiate static fonts from a variable build process results in OTF fonts with CFF2 tables instead of CFF tables. Since these have compatibility issues with some systems and software, it is preferable to build static OTF fonts independent of the variable build process, using a separate set of instance UFOs and a dedicated YAML configuration file.

@khaledhosny I presume there is no easy way to generate CFF table instance fonts from the variable build path?

**Comment by khaledhosny** [comment]
FontTools does not support this currently. AFDKO’s tx seem to support it, and so does the cffsubr module that wraps it. I’ll see if using cffsubr does the trick.

**Comment by tiroj** [comment]
Fix confirmed. Thanks, @khaledhosny 

I notice that I get a small size improvement if I build the statics separately, from individual UFOs, rather than instantiated from the variable build stream, so may opt to do that for at least some projects. Being able to build CFF from the variable build stream is definitely convenient, though.
