### ISSUE TITLE
Subset cmap remapping in buuilder config?

### ISSUE THREAD

**Issue by tiroj** [TiroTypeworks/TiroTools#24]
@khaledhosny I occasionally encounter situations in which one or more characters would be better mapped to a different GID in a subset font. Is there a way this could be conveniently supported via the builder config file, e.g. as a mapping list of codepoints to glyph names? [I presume, since this would usually be at the subset level, that the required glyph name would be post .ren renaming, as per the subsetting itself.]

**Comment by khaledhosny** [comment]
I think we can do that in the post processing step after subsetting. Do you have a preferred way to do this mapping? I guess an external file would be best. I guess something like this:

```
0xNNNN glyphname
```

It would then loop over cmap subtables and check if 0xNNNN exists in the subtable and update the mapping, should it also add a new mapping of none exists?

**Comment by tiroj** [comment]
An external file is probably right for this. Yes, it would be good to be able to add new mappings, although I can’t think of a specific use case at the moment.
