### ISSUE TITLE
Unicode Range and Codepage bits in subset fonts

### ISSUE THREAD

**Issue by tiroj** [TiroTypeworks/TiroTools#26]
Subset fonts created by the Builder do not have updated OS/2 table Unicode Range or Codepage bits, but instead maintain the settings from the superset source. @khaledhosny is there a way to update these, either explicitly from the subset text file, or automatically by setting the bits against what is present in the subset cmap table?

**Comment by khaledhosny** [comment]
#29 updates Unicode ranges, but FontTools does not have code to update code pages and it needs a bit of data tables for the code pages so it would be an overkill to implement it here. There is an open FontTools pull request (https://github.com/fonttools/fonttools/pull/2607), I’ll try to complete and merge it and we can then use that here.
