### ISSUE TITLE
VFJ-to-VOLT skipping single-glyph classes?

### ISSUE THREAD

**Issue by tiroj** [TiroTypeworks/TiroTools#37]
@khaledhosny 

I’ve not fully diagnosed this, but I think the VFJ-to-VOLT tool --kerning function might be skipping FL classes that only contain a single glyph when writing the .vtg group file, but retains the reference to such classes when writing the .vtl lookup file. This means I need to manually add the single-glyph groups in VOLT before the lookup will compile.

FL kern/dist sources occasionally contain single-glyph classes, sometimes because I am planning for anticipated glyph set additions that would be added to that class, but more often because a particular kerning source is a subset of a larger one that included more glyphs in that class.

**Comment by tiroj** [comment]
Hmm. While kerning classes including single glyphs seem consistently skipped, other kerning classes referenced in the .vtl kerning lookups are being skipped in the .vtg output from VFJ-to-VOLT. I can’t spot a pattern.

**Comment by khaledhosny** [comment]
Does this happen to a VFJ file or all of them?

**Comment by tiroj** [comment]
This is going from a VFJ file to .vtg using vfj-to-volt.py. The kern lookups seem complete based on the VFJ, but some of the classes referenced in the VFJ and the kerning lookups are being skipped in the groups file.

**Comment by khaledhosny** [comment]
I think this should be fixed now (we were writing out groups involved in class kerning). Please re-open if there are still missing groups.

**Comment by tiroj** [comment]
Tested this, and it still seems to be a problem. A few, apparently random kerning groups are not being written but are referenced in lookups.

I’ll send you the VFJ for testing.

**Comment by tiroj** [comment]
Ignore that. Different issue in my sources.
