### ISSUE TITLE
Error in conversion of GPOS cpsp lookup

### ISSUE THREAD

**Issue by tiroj** [TiroTypeworks/TiroTools#5]
Converting a .vtp including a cap-spacing (cpsp) GPOS feature, I got this result:

```
lookup x.cpsp useExtension {
    pos @Uppercase-cpsp <50 None 100 None>;
} x.cpsp;
```

This caused a fail in compilation, because those 'None' values should be '0' (zero).

The original .vtp lookup code is

```
DEF_LOOKUP "x.cpsp" PROCESS_BASE PROCESS_MARKS ALL DIRECTION LTR
IN_CONTEXT
END_CONTEXT
AS_POSITION
ADJUST_SINGLE GROUP "Uppercase-cpsp" BY POS ADV 100 DX 50 END_POS
END_ADJUST
END_POSITION
```

I _think_ the fix here needs to be that any GPOS values not explicit in the .vtp source need to be presumed to be zero in the .fea.

**Comment by khaledhosny** [comment]
This is a feaLib bug, I submitted a fix to FontTools in https://github.com/fonttools/fonttools/pull/1599
