### ISSUE TITLE
Update Builder readme with hinting option keys

### ISSUE THREAD

**Issue by tiroj** [TiroTypeworks/TiroTools#52]
@khaledhosny When you have a chance, can you please update the readme for the Builder tool to provide instructions and examples for the new hinting and gasp table controls? Thanks.

**Comment by khaledhosny** [comment]
I already did that, they are at the bottom of https://github.com/TiroTypeworks/TiroTools/tree/master/Builder#readme

**Comment by tiroj** [comment]
Thank you. I realised I had not yet pulled to the device on which I was looking.
